CREATE TYPE public.activity_actor_kind AS ENUM ('system', 'client', 'member');
CREATE TABLE public.activity_events (id uuid DEFAULT gen_random_uuid() NOT NULL, org_id uuid NOT NULL, actor_id uuid, actor_kind public.activity_actor_kind NOT NULL, type text NOT NULL, summary text NOT NULL, project_id uuid, entity_type text, entity_id uuid, payload jsonb DEFAULT '{}'::jsonb NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);
ALTER TABLE public.activity_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_events ADD CONSTRAINT activity_events_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.activity_events ADD CONSTRAINT activity_events_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id) ON DELETE CASCADE;
ALTER TABLE public.activity_events ADD CONSTRAINT activity_events_pkey PRIMARY KEY (id);
ALTER TABLE public.activity_events ADD CONSTRAINT activity_events_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;
GRANT ALL ON public.activity_events TO anon;
GRANT ALL ON public.activity_events TO authenticated;
GRANT ALL ON public.activity_events TO service_role;
CREATE INDEX activity_events_org_created_idx ON public.activity_events (org_id, created_at DESC);
CREATE INDEX activity_events_project_id_idx ON public.activity_events (project_id);
CREATE POLICY members_insert_activity_events ON public.activity_events FOR INSERT TO authenticated WITH CHECK ((public.has_org_role(org_id, ARRAY['owner'::public.user_role, 'admin'::public.user_role, 'member'::public.user_role]) AND (actor_id = ( SELECT auth.uid() AS uid))));
CREATE POLICY staff_view_activity_events ON public.activity_events FOR SELECT TO authenticated USING (public.has_org_role(org_id, ARRAY['owner'::public.user_role, 'admin'::public.user_role, 'member'::public.user_role]));
CREATE TABLE public.clients (id uuid DEFAULT gen_random_uuid() NOT NULL, org_id uuid NOT NULL, name text NOT NULL, contact_name text, contact_email text, created_at timestamp with time zone DEFAULT now() NOT NULL);
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ADD CONSTRAINT clients_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id) ON DELETE CASCADE;
ALTER TABLE public.clients ADD CONSTRAINT clients_org_id_name_key UNIQUE (org_id, name);
ALTER TABLE public.clients ADD CONSTRAINT clients_pkey PRIMARY KEY (id);
GRANT ALL ON public.clients TO anon;
GRANT ALL ON public.clients TO authenticated;
GRANT ALL ON public.clients TO service_role;
CREATE INDEX clients_org_id_idx ON public.clients (org_id);
CREATE POLICY owners_admins_write_clients ON public.clients TO authenticated USING (public.has_org_role(org_id, ARRAY['owner'::public.user_role, 'admin'::public.user_role])) WITH CHECK (public.has_org_role(org_id, ARRAY['owner'::public.user_role, 'admin'::public.user_role]));
CREATE POLICY staff_view_clients ON public.clients FOR SELECT TO authenticated USING (public.has_org_role(org_id, ARRAY['owner'::public.user_role, 'admin'::public.user_role, 'member'::public.user_role]));
ALTER TABLE public.deliveries ADD COLUMN due_date date;
ALTER TABLE public.deliveries ADD COLUMN created_at timestamp with time zone DEFAULT now() NOT NULL;
CREATE INDEX deliveries_org_status_due_idx ON public.deliveries (org_id, status, due_date);
ALTER TABLE public.plans ADD COLUMN seats smallint;
ALTER TABLE public.plans ADD CONSTRAINT plans_seats_check CHECK (seats IS NULL OR seats > 0);
-- Backfilled here rather than at INSERT time in 20260729102721_seed_plans.sql, which
-- runs before this column exists. Free has no seat cap (null); Starter/Studio/Agency
-- match the design's seats line, per plan name regardless of billing period.
UPDATE public.plans SET seats = 5  WHERE name = 'Starter' AND duration_months IN (1, 12);
UPDATE public.plans SET seats = 10 WHERE name = 'Studio'  AND duration_months IN (1, 12);
UPDATE public.plans SET seats = 15 WHERE name = 'Agency'  AND duration_months IN (1, 12);
ALTER TABLE public.project_allocations ADD COLUMN effective_to date;
ALTER TABLE public.project_allocations ADD CONSTRAINT project_allocations_check CHECK (effective_to IS NULL OR effective_to >= effective_from);
ALTER TABLE public.projects ADD COLUMN client_org_id uuid;
ALTER TABLE public.projects ADD CONSTRAINT projects_client_org_id_fkey FOREIGN KEY (client_org_id) REFERENCES public.clients(id) ON DELETE SET NULL;
CREATE INDEX projects_client_org_id_idx ON public.projects (client_org_id);
