ALTER TABLE public.invoices ADD COLUMN period_start date;
ALTER TABLE public.invoices ADD COLUMN period_end date;
ALTER TABLE public.invoices ADD CONSTRAINT invoices_check CHECK (period_end IS NULL OR period_end >= period_start);
CREATE UNIQUE INDEX invoices_project_period_key ON public.invoices (project_id, period_start) WHERE period_start IS NOT NULL;
ALTER TABLE public.memberships ADD COLUMN default_rate numeric(10,2);
ALTER TABLE public.memberships ADD CONSTRAINT memberships_default_rate_check CHECK (default_rate IS NULL OR default_rate >= 0::numeric);
ALTER TABLE public.memberships ADD COLUMN cost_rate numeric(10,2);
ALTER TABLE public.memberships ADD CONSTRAINT memberships_cost_rate_check CHECK (cost_rate IS NULL OR cost_rate >= 0::numeric);
ALTER TABLE public.time_entries ADD COLUMN invoice_id uuid;
ALTER TABLE public.time_entries ADD CONSTRAINT time_entries_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id) ON DELETE SET NULL;
CREATE INDEX time_entries_invoice_id_idx ON public.time_entries (invoice_id);
