SET check_function_bodies = false;
REVOKE ALL ON FUNCTION public.revoke_user_sessions(uuid) FROM anon;
REVOKE ALL ON FUNCTION public.revoke_user_sessions(uuid) FROM authenticated;
CREATE TABLE public.user_preferences (user_id uuid NOT NULL, locale text DEFAULT 'en-GB'::text NOT NULL, time_zone text, last_device_time_zone text, theme text, weekly_digest boolean DEFAULT false NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
ALTER TABLE public.user_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_preferences ADD CONSTRAINT user_preferences_last_device_time_zone_check CHECK (last_device_time_zone IS NULL OR char_length(last_device_time_zone) >= 1 AND char_length(last_device_time_zone) <= 64);
ALTER TABLE public.user_preferences ADD CONSTRAINT user_preferences_locale_check CHECK (locale = ANY (ARRAY['en-GB'::text, 'en-US'::text]));
ALTER TABLE public.user_preferences ADD CONSTRAINT user_preferences_pkey PRIMARY KEY (user_id);
ALTER TABLE public.user_preferences ADD CONSTRAINT user_preferences_theme_check CHECK (theme IS NULL OR (theme = ANY (ARRAY['light'::text, 'dark'::text, 'system'::text])));
ALTER TABLE public.user_preferences ADD CONSTRAINT user_preferences_time_zone_check CHECK (time_zone IS NULL OR char_length(time_zone) >= 1 AND char_length(time_zone) <= 64);
ALTER TABLE public.user_preferences ADD CONSTRAINT user_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;
GRANT ALL ON public.user_preferences TO anon;
GRANT ALL ON public.user_preferences TO authenticated;
GRANT ALL ON public.user_preferences TO service_role;
CREATE INDEX user_preferences_weekly_digest_idx ON public.user_preferences (user_id) WHERE weekly_digest;
CREATE POLICY insert_own_preferences ON public.user_preferences FOR INSERT TO authenticated WITH CHECK ((user_id = ( SELECT auth.uid() AS uid)));
CREATE POLICY require_mfa_when_enrolled ON public.user_preferences AS RESTRICTIVE TO authenticated USING (( SELECT public.mfa_satisfied() AS mfa_satisfied)) WITH CHECK (( SELECT public.mfa_satisfied() AS mfa_satisfied));
CREATE POLICY update_own_preferences ON public.user_preferences FOR UPDATE TO authenticated USING ((user_id = ( SELECT auth.uid() AS uid))) WITH CHECK ((user_id = ( SELECT auth.uid() AS uid)));
CREATE POLICY view_own_preferences ON public.user_preferences FOR SELECT TO authenticated USING ((user_id = ( SELECT auth.uid() AS uid)));
